name: Labeler
on:
  pull_request_review:
    types: [submitted]

jobs:
  LabelingJob:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add Label Ready to Merge
        if: |
          github.event.review.state == 'approved' &&
          (github.event.comment.user.login == 'LeonMontealegre' ||
           github.event.review.user.login == 'LeonMontealegre')
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: |
            Status: Ready to Merge
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Remove Changes Requested Label for Ready to Merge 
        if: |
          github.event.review.state == 'approved' &&
          (github.event.comment.user.login == 'LeonMontealegre' ||
           github.event.review.user.login == 'LeonMontealegre')
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: |
            Status: Changes Requested
      - name: Remove Awaiting Review Label for Ready to Merge 
        if: |
          github.event.review.state == 'approved' &&
          (github.event.comment.user.login == 'LeonMontealegre' ||
           github.event.review.user.login == 'LeonMontealegre')
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: |
            Status: Awaiting Review
      - name: Add Label Changes Requested
        if: |
          github.event.review.state == 'changes_requested' &&
          (github.event.comment.user.login == 'LeonMontealegre' ||
           github.event.review.user.login == 'LeonMontealegre')
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: |
            Status: Changes Requested
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Remove Ready to Merge Label for Changes Requested
        if: |
          github.event.review.state == 'changes_requested' &&
          (github.event.comment.user.login == 'LeonMontealegre' ||
           github.event.review.user.login == 'LeonMontealegre')
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: |
            Status: Ready to Merge
      - name: Remove Awaiting Review Label for Changes Requested
        if: |
          github.event.review.state == 'changes_requested' &&
          (github.event.comment.user.login == 'LeonMontealegre' ||
           github.event.review.user.login == 'LeonMontealegre')
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: |
            Status: Awaiting Review
